FLAGS = -Wall -Wextra -Werror
NAME = bsq
SRC_NAME = main.c
SRC_FT = ft.c

main: $(SRC_NAME) $(SRC_FT)
	cc $(FLAGS) $(SRC_NAME) $(SRC_FT) -o $(NAME)

clean: $(NAME)
	rm $(NAME)

fclean: $(NAME)
	rm $(NAME)
